version: "3.8"
services:
  employee:
    image: employee
    ports:
      - "8070:8070"
    depends_on:
      - employee-db
    networks:
      - employee-network

  employee-db:
    image: mysql:8.0.0
    restart: always
    env_file:
      - ./.env
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
    networks:
      - employee-network
